import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { euclid } from "@/font";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${euclid.className} bg-[#F7F7F7]`}>{children}</body>
    </html>
  );
}
